In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

In [2]:
# Question 1
from datascience import *
strings = make_array('Will','Cooper','Texas','Blue') #Create an array with needed information
print(strings)

upper_strings = np.char.upper(strings) #Make the array uppercase
print(upper_strings)

letter_count = np.char.count(strings, 'a') #Count the occurances of 'a' in each string
print(letter_count)

word_length = np.char.count(strings, '') #Determine the length of each string
print(word_length)

['Will' 'Cooper' 'Texas' 'Blue']
['WILL' 'COOPER' 'TEXAS' 'BLUE']
[0 0 1 0]
[5 7 6 5]


In [3]:
#Question 2
odd_numbers = np.arange(1,45,4) #Create the array with every other odd
print(odd_numbers)

odd_num_sum = np.sum(odd_numbers) #Sum the array
print(odd_num_sum)

odd_num_prod = np.prod(odd_numbers.astype(float)) #Determine the product of the array using as type to avoid error
print(odd_num_prod)

odd_num_log = np.log(odd_numbers) #Take the natural log of each element in the array
print(odd_num_log)

sum_diff = np.sum(np.diff(odd_numbers)) #Sum the difference of all the elements
print(sum_diff)

[ 1  5  9 13 17 21 25 29 33 37 41]
231
7579867420125.0
[0.         1.60943791 2.19722458 2.56494936 2.83321334 3.04452244
 3.21887582 3.36729583 3.49650756 3.61091791 3.71357207]
40
