In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Question 1 

Create an array containing 4 string elements: your first name, your last name, your birth
state and your favorite color.

a. Use a numpy function to make all elements uppercase.

In [4]:
strings = make_array('Will','Cooper','Texas','Blue')
print(strings)

upper_strings = np.char.upper(strings) #Make the array uppercase
print(upper_strings)

['Will' 'Cooper' 'Texas' 'Blue']
['WILL' 'COOPER' 'TEXAS' 'BLUE']


b. Use a numpy function to count the number of times the letter “a” appears in each
element of your array.

In [5]:
letter_count = np.char.count(strings, 'a') 
print(letter_count)

[0 0 1 0]


c. Optional: Use a numpy function to find the length of each element in the array.
You may need to Google this.

In [6]:
word_length = np.char.count(strings, '')
print(word_length)

[5 7 6 5]


## Question 2

Create an array containing EVERY OTHER odd number starting with 1 and ending with
(and including) 41.

a. Use numpy to find the sum and the product of the elements of this array. NOTE:
This will require you to convert the elements of your array to floats using the
astype method.

In [8]:
odd_numbers = np.arange(1,45,4)
print(odd_numbers)

odd_num_sum = np.sum(odd_numbers)
print(odd_num_sum)

odd_num_prod = np.prod(odd_numbers.astype(float)) 
print(odd_num_prod)

[ 1  5  9 13 17 21 25 29 33 37 41]
231
7579867420125.0


b. Use numpy to take the natural log of each element.

In [9]:
odd_num_log = np.log(odd_numbers)
print(odd_num_log)

[0.         1.60943791 2.19722458 2.56494936 2.83321334 3.04452244
 3.21887582 3.36729583 3.49650756 3.61091791 3.71357207]


c. Optional: The numpy function np.diff finds the difference between adjacent
elements of an array. Find the SUM of adjacent elements of this array.

In [11]:
sum_diff = np.sum(np.diff(odd_numbers)) 
print(sum_diff)

40
